### ISSUE TITLE
Ayuda Namespace prefix wcf on GetNumberingRange is not defined

### ISSUE THREAD

**Issue by chelipe93** [FuriosoJack/pyWSSE-Dian2#2]
Hola @FuriosoJack, estoy tratando de implementar tu código para el reporte de documentos de soporte a la DIAN con software propio, pero estoy obteniendo este error luego de poner la clave p12 y los datos del endpoint GetNumberingRange:

lxml.etree.XMLSyntaxError: Namespace prefix wcf on GetNumberingRange is not defined, line 1, column 23

Agradeceria tu ayuda.

**Comment by FuriosoJack** [comment]
Hola @chelipe93 si claro si gustas me me escribes a donjuanc@codwelt.com y coordinamos una reunión para revisar el tema de la firma.
